### ISSUE TITLE
File for meta-data on counties

### ISSUE THREAD

**Issue by geanders** [my1120/Hurricane_Analysis#1]
It looks like the ihapps website  might have come down, so we might need to pull that data from somewhere else.

**Comment by my1120** [comment]
Oh?!

And will we meet at 2:00 or 2:30 today? Thanks!

Best,
Meilin

On Aug 19, 2016, at 12:14 PM, Brooke Anderson <notifications@github.com<mailto:notifications@github.com>> wrote:

It looks like the ihapps website might have come down, so we might need to pull that data from somewhere else.

**Comment by geanders** [comment]
2:00
